### ISSUE TITLE
Broken link of models

### ISSUE THREAD

**Issue by Bardo91** [D-X-Y/caffe-faster-rcnn#20]
I am trying to fetch the models for testing the code but I cant find the models. When I try to run the script 
`fetch_imagenet_models.sh` it says `404 Not Found` and I cannot reach the [webpage](http://www.cs.berkeley.edu/~rbg/faster-rcnn-data/imagenet_models.tgz) if I try to go manually.

**Comment by D-X-Y** [comment]
These models are previously provied by https://github.com/rbgirshick/py-faster-rcnn.
If you want to train the model, you can direcly use the pre-trained model from Caffe Model Zoo.
If you want to test a trained model, you can try the model on https://github.com/rbgirshick/py-faster-rcnn/tree/master/models, but need to modify some configures since it's a COCO model.

**Comment by Bardo91** [comment]
Ok! That makes sense. So, I am closing the issue. Very thanks
